{
	"data": "ENC[AES256_GCM,data:krNquVVDLJZRUJ4CyNo3zbrqchFBnermnvuW3339terrINV+A0MSfN+f3qbNdUWklwujKIPCvvjowZxZwJK71ncogpmuijDjkYRbpha6HSAdp1wjdj9mHNFiSGZm/FjXknSoxcrLrSXLJ+YDI9GkqpJ51UN0wvLD6ADXgcU1dTnxdzf/9/xX7RjxKDo4e4f2KLokA2TZMhi41Sa2pWOaBc7ZFT+d25a1h3rShbMK8BDEeGTMraWuaIm76kUgjRJi1OSdLk69a/a8alNPeWox/G2tWypMSYqvlLXnnMorE/4UYbkV09vrzb7F5Cv4/mqDVyr4e5kHZ0bs/5ZgTCXi9BvLLT0CnWC+9pCrRy/N/qHjNgffR69Mngh6Ty0mgsKKK3kmMITxXUnjhdooScR+VYErAF4clY1d7LuvffJG9obZg4BVl1xu+DrAAHKJJId5cgRl0sTaEsY66h7VSTtw1xjCfaeGSYamE2K/EuMay+GzUvtSVt2fUJQQ/uxPTj0DomNUsMSKdI7K23A0YEqo58tEJb4+CHgrOvI/25e+o5gyjRdDCe849tcQt8hbvGPMIONqcxAQz2Wa2VGeE3JZulvsILNdp31r56gmLfw1hsdnV9uWbzEbAZ6LNRBlJ/mXkCzCXMGouJRoLuGEkpfhCl98MUEX3etIdu6Ir9iKAy87MTZ/WW1yK9kzMdKd+YYU56E=,iv:KqJbHa2yjBhMq2IDhjMjwxqUTfluLQu43CxrHfqNkb4=,tag:wLfqFdih8oGg5yaXzvbC3Q==,type:str]",
	"sops": {
		"age": [
			{
				"recipient": "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIOEFLUkyeaK8ZPPZdVNEmtx8zvoxi7xqS2Z6oxRBuUPO",
				"enc": "-----BEGIN AGE ENCRYPTED FILE-----\nYWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHNzaC1lZDI1NTE5IDltTWRrUSBCUjFJ\nYXB0ZkRudjZRcXBRY3RZNUNFVk1aUHI1eDF3MENvNnNqNFF1akI0CnZBN1pqLzBD\nZnIyVGs1V0hxREJtTEllSURLQ3JJNVBNcDhTQTBYOGxjQWcKLS0tIExLL2pPeVVR\nVW9UdmFMdUlNMGxRS1Ura251QzEvMTQ0c01sU0JPVmxtN1UKQxAjmEgeSgocSA9Q\nbngYGWx6sSomaBaqBRWhxCeyvnP+M5sZkBI6bEDVvfqly6yfPb43xKxh4LrOv0te\nfJzWcg==\n-----END AGE ENCRYPTED FILE-----\n"
			},
			{
				"recipient": "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIB28jpN+h5euh3NtdN+A+EtqgIatC22e4i1TPTioKire",
				"enc": "-----BEGIN AGE ENCRYPTED FILE-----\nYWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHNzaC1lZDI1NTE5IHJNY1d1ZyBmZUxB\na2h2WGVySHQ5RFFTQmloT2pYMTZVcU8vc25wbUZmUWRvK25TMnpvClE4QVZEdnpB\nVDEzSnIxN0ZpTkxyclZRL1NRNHNJbVhvRVdCSUNubzBNMG8KLS0tIEZWbk5sc3U1\nOERuZVBPZ1g2U2VKSVF2dFJ4OUEyeW91V3VFMHdPaVhWZUEKLbQAvuT6WeoJl49G\ntmPO4rAiGFc2/Psoq1ShBRk/RbyBB9248ttaiyLgVNFnE0J825ade5B2wcf6+Pfq\nZV2UEw==\n-----END AGE ENCRYPTED FILE-----\n"
			},
			{
				"recipient": "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIMb5G/ieEYBOng66YeyttBQLThyM6W//z2POsNyq4Rw/",
				"enc": "-----BEGIN AGE ENCRYPTED FILE-----\nYWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHNzaC1lZDI1NTE5IFhGYmtrZyA4RjNs\nWlYvc0tEN2hOUTA5SEV6MUhTeFViRTBqVWJLcGVDZ0JROCtONlQ0CnU0Z2FWQUlw\nakt0dk1nbVFHaVlyMjBqS3hCSDdHZEYwT0pXaXhOclFvSjgKLS0tIG9ZZUQ2dTI5\nWFVJanhac0QxVHM2b04wNE1jcHdHa3JJYzBlTE1iS1ZPTHcKZPvA9MwYT4JfG3/F\nqSI09TWeEv7TAWGeZr6OS++egtpdVoM3hF8s1B1TZb3bf/BMqo49NEkvD56pOKvo\no0jjHw==\n-----END AGE ENCRYPTED FILE-----\n"
			}
		],
		"lastmodified": "2025-12-06T08:16:57Z",
		"mac": "ENC[AES256_GCM,data:CanRJamcOHb/rfQY9l6EDQSXHTFex2bvUy60MetTtjYNbIHOOXhNvvkNnO4vD6Wrq/ciZGyeqY7OB5+6bCpogVKbdhyyUA2gZM0dxymvPywk/T1cBiqCMNN9JBgrL8BqhBCVtGbtY82MnhK7c4caOqlxmhqRwyELFW1XwwTrqqI=,iv:PGx/qQr3XBt+WqQPKe3SYZTCWHbEeq+jOX43qRdcnPU=,tag:AaOG/jj21DKHP0Oeybc60g==,type:str]",
		"unencrypted_suffix": "_unencrypted",
		"version": "3.11.0"
	}
}
