{
	"data": "ENC[AES256_GCM,data:dMHcyiqxP7GFLgFpW4QvwA9f5ZCvFpJ8Kb+SpZmd1iWt3LQb4mYsK/CbqnqinNC7IKSkjE5ftLupCJJA2V+8HnRDKjwNyuaGZn0qoty8oJ1ttzZ42OXPX7tn/18Ig2YVv9QhWix5oiwKt03t7O/ZGhC56rSVtYebmoZNhidQRJgCZaDpHZyDF74POYpsaaU1eV5UmoI3iyMHAfD1B3ryQ9PBcNprFo5zUW6HG8BG9+M6l9r3SKIjPiyfoimslmXrOowbIapPkyn8rjXltv65RpU5SbxJ4E+o8w/M/Gewbg/BvEzb5Cv/6BmU9Kdrks1F9BuPHRi7xvAtkaa0IkQUANWdPJg1vhvJnmpwfFfjkOzHkzAjay0gEs4e3ffD3FouWPEic0yhqBdyhYJUdaJoW+3jO0r2WgwkH8J7YYp8vJTIn4GK2fRUF+JGBTPEkGqwL6YywDmqAM6tMOqB9UAKb1zjDuQkQpsPw7bShOu+jYLVfKFgHETZrA9pZ1M4qP01aYAJ33Clj7E4o6MbHq+JCDmo1zgI7gFfOlsATUpq8WlL2snuMyktoTe0EZD0fh4rfRvHCPYNRHgSS3xldXlr43WYc2T58xdgqo0kDEnL9xPeaO+7tHs+hRw177MZoQKQjOFMgMkSeXNydp96NtRUar8Z,iv:/0GM/1InePGUraWpEzOJMXw5NngwVJHu69Vqpq/8ass=,tag:7VMG31bOgepWR4uHF6Beyg==,type:str]",
	"sops": {
		"age": [
			{
				"recipient": "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIOEFLUkyeaK8ZPPZdVNEmtx8zvoxi7xqS2Z6oxRBuUPO",
				"enc": "-----BEGIN AGE ENCRYPTED FILE-----\nYWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHNzaC1lZDI1NTE5IDltTWRrUSBCUjFJ\nYXB0ZkRudjZRcXBRY3RZNUNFVk1aUHI1eDF3MENvNnNqNFF1akI0CnZBN1pqLzBD\nZnIyVGs1V0hxREJtTEllSURLQ3JJNVBNcDhTQTBYOGxjQWcKLS0tIExLL2pPeVVR\nVW9UdmFMdUlNMGxRS1Ura251QzEvMTQ0c01sU0JPVmxtN1UKQxAjmEgeSgocSA9Q\nbngYGWx6sSomaBaqBRWhxCeyvnP+M5sZkBI6bEDVvfqly6yfPb43xKxh4LrOv0te\nfJzWcg==\n-----END AGE ENCRYPTED FILE-----\n"
			},
			{
				"recipient": "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIB28jpN+h5euh3NtdN+A+EtqgIatC22e4i1TPTioKire",
				"enc": "-----BEGIN AGE ENCRYPTED FILE-----\nYWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHNzaC1lZDI1NTE5IHJNY1d1ZyBmZUxB\na2h2WGVySHQ5RFFTQmloT2pYMTZVcU8vc25wbUZmUWRvK25TMnpvClE4QVZEdnpB\nVDEzSnIxN0ZpTkxyclZRL1NRNHNJbVhvRVdCSUNubzBNMG8KLS0tIEZWbk5sc3U1\nOERuZVBPZ1g2U2VKSVF2dFJ4OUEyeW91V3VFMHdPaVhWZUEKLbQAvuT6WeoJl49G\ntmPO4rAiGFc2/Psoq1ShBRk/RbyBB9248ttaiyLgVNFnE0J825ade5B2wcf6+Pfq\nZV2UEw==\n-----END AGE ENCRYPTED FILE-----\n"
			},
			{
				"recipient": "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIMb5G/ieEYBOng66YeyttBQLThyM6W//z2POsNyq4Rw/",
				"enc": "-----BEGIN AGE ENCRYPTED FILE-----\nYWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHNzaC1lZDI1NTE5IFhGYmtrZyA4RjNs\nWlYvc0tEN2hOUTA5SEV6MUhTeFViRTBqVWJLcGVDZ0JROCtONlQ0CnU0Z2FWQUlw\nakt0dk1nbVFHaVlyMjBqS3hCSDdHZEYwT0pXaXhOclFvSjgKLS0tIG9ZZUQ2dTI5\nWFVJanhac0QxVHM2b04wNE1jcHdHa3JJYzBlTE1iS1ZPTHcKZPvA9MwYT4JfG3/F\nqSI09TWeEv7TAWGeZr6OS++egtpdVoM3hF8s1B1TZb3bf/BMqo49NEkvD56pOKvo\no0jjHw==\n-----END AGE ENCRYPTED FILE-----\n"
			}
		],
		"lastmodified": "2025-11-08T13:03:12Z",
		"mac": "ENC[AES256_GCM,data:6g9EKsiiDYFXsw5hhp1veIuziS5ypTH6yVJ9CduP5/0QosHIevtxbqOm17V/aUyntYMUFtfXbF1r1hMFXNT6Jitjz/Wmh5oMxupxIjt5M1cxDb8SKYrWyrxMBPlmA/Wkbj3ahlVcy+0BKxTVpXVLhnBObN7x8fy/1sqFk3Azi2g=,iv:Li83o/t3LSfN057d0tgt1uNez3HoSb+BYJ8Wa4PxlK0=,tag:zqqLrA7Ka1oH7b17zQoMVg==,type:str]",
		"unencrypted_suffix": "_unencrypted",
		"version": "3.11.0"
	}
}
